### ISSUE TITLE
Speeding up Kconfig parsing (caching)

### ISSUE THREAD

**Issue by Lekensteyn** [ulfalizer/Kconfiglib#18]
Loading Kconfigs took about 4-5s, with this quick & dirty [pickle][0] trick I halved that:

```py
import pickle, sys
import kconfiglib

cache_file = 'picked-kconfig'
try:
    conf = pickle.load(open(cache_file, 'rb'))
except:
    sys.setrecursionlimit(100000)
    conf = kconfiglib.Config()
    pickle.dump(conf, open(cache_file, 'wb'))
```

The resulting "picked-kconfig" is 8.8M for Linux v4.2-rc5. It can probably be further improved by setting appropriate `__getstate__` and `__setstate__` magic methods, but for me this was already a nice speed boost for testing purposes.

Is this something you have considered before?

 [0]: https://docs.python.org/3/library/pickle.html

**Comment by ulfalizer** [comment]
A drawback would be that it wouldn't be able to handle environment variables changing between runs. Check the top-level Kconfig file for example, which `source`s the Kconfig for a particular arch by looking at `$SRCARCH`. There are other examples too, and Kconfiglib can't know about them in advance (especially since it supports other projects besides the kernel).

What's your system specs by the way? Loading a Config for a particular architecture takes less than a second on my 2600k Core i7 with CPython. Just to check that it's not being abnormally slow.

**Comment by Lekensteyn** [comment]
Ah, I ran it with `Kconfiglib` next to the `linux` repo (instead of a patch inside) and the timing included a 1s delay for `make kernelversion` in the wrapper script:

```python
import sys, os.path, subprocess

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
import kconfiglib
class KernelVersion(object):
    """Lazy evaluation of kernel version finder."""
    def __str__(self):
        return subprocess.check_output(
            ["make", "kernelversion"],
            universal_newlines=True).strip()

for k, v in {
    'ARCH': "x86_64",
    'SRCARCH': "x86",
    'KERNELVERSION': KernelVersion(),
}.items():
    if not k in os.environ:
        os.environ[k] = str(v)
```

Anyway for my purpose, the `SRCARCH`, `ARCH` and `KERNELVERSION` variables and Kconfig files are static (they do not change). I was trying to make [a tool that helps me in making a smaller kernel config](https://github.com/Lekensteyn/Kconfiglib/blob/hackery/examples/count_children.py), so the only thing that constantly changes was the generator script and (later) possibly the .config file.

If those conditions are not valid, then serialization using pickle can indeed not be used. But in the use case above, it does :smiley:.
___
The following tests are described by this Python code which were ran after reading the git tree from a SSD into memory:

 - Config: `import kconfiglib; kconfiglib.Config()`
 - Config+pickle.dump: `import kconfiglib, pickle, sys; c=kconfiglib.Config(); sys.setrecursionlimit(100000); pickle.dump(c, open("/tmp/x","wb"))`
 - pickle.load: `import kconfiglib, pickle, sys; c=pickle.load(open("/tmp/x", "rb"))`

The `bash` command is:

    for i in {0..9}; do
        time PYTHONPATH=../Kconfiglib \
          ARCH=x86_64 SRCARCH=x86 KERNELVERSION=4.2.0-rc5 \
          python -c 'import kconfiglib; kconfiglib.Config()';
    done

For an i5-560M (used in the original report and throughout development):

| test (n=10, Py3.4.10) | avg    | min    | max    | stdDev  |
| --------------------- | ------ | ------ | ------ | ------- |
| Config                | 3.611s | 3.513s | 3.76s  | 0.0871s |
| Config+pickle.dump    | 4.333s | 4.213s | 4.537s | 0.1089s |
| pickle.load           | 1.693s | 1.618s | 1.82s  | 0.0595s |

For an i7-3770 (for comparison):

| test (n=10, Py3.4.10) | avg    | min    | max    | stdDev  |
| --------------------- | ------ | ------ | ------ | ------- |
| Config                | 1.324s | 1.306s | 1.345s | 0.0138s |
| Config+pickle.dump    | 1.627s | 1.603s | 1.653s | 0.0160s |
| pickle.load           | 0.616s | 0.602s | 0.63s  | 0.0105s |

The resulting `/tmp/x` file is 7.9MiB by the way.

As you can see, (de)serialization helps a lot with reducing run time for repeated runs with the same Kconfig state, whether it is useful/applicable depends on your use case. Optimizations are probably possible, have not investigated it further.

**Comment by ulfalizer** [comment]
Yeah, those numbers look more reasonable. Parsing the x86 Kconfig takes ~1.3 seconds on my system for 4.2.0-rc5.

Maybe a method `Config.pickle_to_file(file)` could be added, with a docstring that mentions the caveats above. Did you try passing `pickle.HIGHEST_PROTOCOL` to `pickle.dump()` by the way? Not sure if it makes much of a difference for Python 3, but might be helpful for Python 2. I'm not a pickle expert. :)

Setting new user values (via `Config.load_config()` or `Symbol.set_user_value()`) does not require reparsing the Kconfig files. Kconfiglib is optimized for workflows where you parse the Kconfigs once at startup and then muck about with the user values in various ways. If you set things things up so that Kconfiglib handles the changing of the values too, then things should be very speedy. I can see how that might be tricky though.

That's a cool script by the way. Tell me when you're happy with it and I could add it as an example. :)

**Comment by Lekensteyn** [comment]
Higher pickle protocol versions seem more efficient (time and space-wise). Not a pickle expert either though :) See below for numbers.

The Tree logic was inspired by Pythons html.parser interface which imo is a bit nicer if you want to process nodes one-by-one. Implementation of CountingTree was straightforward after that. Then the HtmlTree came... which is a mess at the moment, so I don't know if it will be cleaned up to serve as nice example ;) I've put an example of the generated document at https://lekensteyn.nl/files/config-4.2.0-rc5-debug.html

A dynamic interface (GTK+/Qt?) where user selections are immediately propagated would be awesome. Are you aware of such work? The problems with xconfig/nconfig/gconfig/menuconfig are:

 - Difficult to explore further dependencies for a config, especially if it is large. Example: I do not use a certain Ethernet driver, yet it is marked as `{M}`. Now I have to open the help, copy/remember the *Selected by* keys, search for it, walk through all menus to get to the option and then return to repeat the process.
 - Not designed for prioritizing minimizing sizes. Example: the `custom_method` module is very small and comprises only a single file whereas the `nouveau` module spans multiple files.
 - Unable to see directly what the effect would be of changing an option. For example, disabling the `CONFIG_ETHERNET` option obviously removes all Ethernet drivers, but some others are less obvious.

Only problem I see is that the time needed for this would not be worth it, the partially reduced configuration above (based on Arch Linux' 4.1.3-1-ARCH config) only took 11m7s to build on the i7-3700 with -j16... this is with full debugging information and KASAN enabled.
___
Python 2.7.10 crashed on all protocol versions 0 up to 2 (`pickle.MAX_PROTOCOL`) with:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1370, in dump
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 419, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 681, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 739, in save_global
    module = whichmodule(obj, name)
  File "/usr/lib/python2.7/pickle.py", line 811, in whichmodule
    if func in classmap:
TypeError: unhashable type: 'dict'
```

Python 2 tests that could be executed:

| test (n=10, Py2.7.10) | avg    | min    | max    | stdDev  |
| --------------------- | ------ | ------ | ------ | ------- |
| Config (i7-3770)      | 1.378s | 1.365s | 1.392s | 0.0091s |
| Config (i5-560M)      | 3.601s | 3.443s | 3.860s | 0.1233s |

i5-560M

| test (n=10, Py3.4.3)  | avg    | min    | max    | stdDev  |
| --------------------- | ------ | ------ | ------ | ------- |
| Config                | 3.439s | 3.350s | 3.540s | 0.0645s |
| Config+pickle.dump(4) | 3.855s | 3.783s | 3.928s | 0.0441s |
| Config+pickle.dump(3) | 4.134s | 4.034s | 4.218s | 0.0574s |
| Config+pickle.dump(2) | 4.168s | 4.104s | 4.300s | 0.0716s |
| Config+pickle.dump(1) | 4.309s | 4.188s | 4.384s | 0.0588s |
| Config+pickle.dump(0) | 4.676s | 4.539s | 4.793s | 0.0710s |
| pickle.load [4] 6.2M  | 1.448s | 1.416s | 1.482s | 0.0244s |
| pickle.load [3] 8.5M  | 1.711s | 1.627s | 1.886s | 0.0780s |
| pickle.load [2] 8.1M  | 1.691s | 1.644s | 1.777s | 0.0419s |
| pickle.load [1] 8.4M  | 1.707s | 1.596s | 1.834s | 0.0733s |
| pickle.load [0] 12M   | 2.084s | 1.997s | 2.177s | 0.0573s |

i7-3770

| test (n=10, Py3.4.3)  | avg    | min    | max    | stdDev  |
| --------------------- | ------ | ------ | ------ | ------- |
| Config                | 1.324s | 1.314s | 1.336s | 0.0078s |
| Config+pickle.dump(4) | 1.503s | 1.493s | 1.509s | 0.0053s |
| Config+pickle.dump(3) | 1.622s | 1.603s | 1.646s | 0.0134s |
| Config+pickle.dump(2) | 1.635s | 1.618s | 1.653s | 0.0108s |
| Config+pickle.dump(1) | 1.677s | 1.658s | 1.695s | 0.0139s |
| Config+pickle.dump(0) | 1.839s | 1.827s | 1.857s | 0.0101s |
| pickle.load [4] 6.3M  | 0.552s | 0.544s | 0.560s | 0.0056s |
| pickle.load [3] 7.9M  | 0.640s | 0.611s | 0.673s | 0.0227s |
| pickle.load [2] 8.1M  | 0.619s | 0.606s | 0.640s | 0.0116s |
| pickle.load [1] 8.4M  | 0.660s | 0.634s | 0.695s | 0.0222s |
| pickle.load [0] 13M   | 0.811s | 0.790s | 0.841s | 0.0180s |

**Comment by ulfalizer** [comment]
Nope, haven't seen anyone build any UI configuration frontends on top of Kconfiglib yet, though some people seemed interested. Check the *At least two things...* notes near the end of the README, though those problems shouldn't be insurmountable.

One thing Kconfiglib still lacks that would make it much more general (and allow for building nice detailed graphs and the like) is interfaces for working with expressions, e.g. from dependencies and `... if <expr>` conditions. Having e.g. a simple interface like `Symbol.get_dependent()` that returns a list of all symbols that "depend on" a symbol intuitively seems like the nicest solution, but unfortunately it gets tricky to usefully define what it means for one symbol to "depend on" another symbol since expressions can involve `&&`, `||`, `=`, etc., and come from different sources like `depends on` and `select`. That's the reason Kconfiglib only provides very high-level interfaces like `Symbol.get_referenced_symbols()` and `Symbol.get_selected_symbols()`.

I've been thinking of simply exposing the internal representation of expressions directly, since the format is pretty simple and easy to understand already (see the docstring for `Config._parse_expr()`). Being able to walk over expressions would allow you to do "anything" re. exploring and processing the configuration (with some effort), which would be very nice. To be honest, I think it should be safe to look at the internal expressions already, since things are unlikely to change in any dramatic way there. I just haven't committed to exposing them yet, and I'm not sure what the best way would be. Adding a gazillion accessors for different expressions might be messy...

W.r.t. minimizing size, did you look at what I did in my thesis (linked from the examples)? I'm not sure if you want to minimize compile time (`make localmodconfig` might be handy there) or minimize the size of the kernel though.

I think you have a bug on line 74 of count_children.py btw. `if not item.is_choice():` should be `if not item.is_choice_symbol()`. A `Symbol` is never a `Choice`. :)

Thanks for the benchmarks!

**Comment by Lekensteyn** [comment]
I did look briefly at your thesis, but I got the impression that its goal was to strip as many options and still have a bootable system, not accounting for other functionality that are not immediately exposed (for example netfilter).

Both minimizing compile time and object sizes was a goal for me, but localmodconfig misses modules which are not loaded (by design). It looks more like a starting point for a configuration while I had the opposite task: given an existing config, try to strip the most significant contributors to size and time.

So far I have not needed the expressions yet, but indeed, for evaluating the results of changing a config option would require this API if I see it correctly. Though it would probably be better to wait for an actual user/need before exposing this API as the requirements can then be better understood. I am getting excited about writing a Qt program now to use this, unfortunately time is lacking :/

Thanks for the bug report, fixed that and updated the sample HTML page. The intent was to consider all Chice symbols as one "selected" or "enabled" option that the user should be worried about. Like the coment above says :-)

Also, many thanks for your work on this library! I first looked at the Kconfig C code (tools/kconfig/), but could not even find the data structures and architecture that hold the config items. Your project on the other hand is well-documented and had some clear examples to get going.

**Comment by ulfalizer** [comment]
> So far I have not needed the expressions yet, but indeed, for evaluating the
> results of changing a config option would require this API if I see it
> correctly. Though it would probably be better to wait for an actual user/need
> before exposing this API as the requirements can then be better understood. I
> am getting excited about writing a Qt program now to use this, unfortunately
> time is lacking :/

It could still by done simply by remembering the old values of all the symbols
and seeing which ones changed afterwards, though it's not the most elegant
approach. Kconfiglib caches calculated values, so it might not even be as
horribly slow as it sounds.

> Thanks for the bug report, fixed that and updated the sample HTML page. The
> intent was to consider all Chice symbols as one "selected" or "enabled" option
> that the user should be worried about. Like the coment above says :-)

Yeah, I guessed that was how it worked. :)

> Also, many thanks for your work on this library! I first looked at the Kconfig
> C code (tools/kconfig/), but could not even find the data structures and
> architecture that hold the config items. Your project on the other hand is
> well-documented and had some clear examples to get going.

No problem! I agree that the C implementation isn't exactly overcommented. ;)
