### ISSUE TITLE
Running script without Makefile patch?

### ISSUE THREAD

**Issue by timur-tabi** [ulfalizer/Kconfiglib#30]
Is it possible to run a script without the Makefile patch?  I want to use Kconfiglib to automate some processes on a variety of cross-compiled kernels, so I would prefer to avoid having to patch all of them.

My goal is to be able to figure out all of the Kconfig options that also need to be set in order for some specific option to be set.  For example, if I want to set CONFIG_DM_THIN_PROVISIONING, then I want a script that tells me that I also need to set CONFIG_MD and CONFIG_BLK_DEV_DM.

If you can help me figure that out, I will be eternally grateful.

**Comment by ulfalizer** [comment]
Hello,

The targets added by the `scripts/kconfig/Makefile` patch are needed to pick up environment variables exported from the Kbuild Makefiles, because those can be referenced in the Kconfig files (via `option env="SOME_ENV_VAR"`).

In practice, I've only ever seen three environment variables being referenced: `ARCH`, `SRCARCH`, and `KERNELVERSION`.

`ARCH` is the architecture (x86, sparc, etc.), `SRCARCH` a subdirectory in `arch/` where files for the ARCH are stored. Usually, `SRCARCH` will match `ARCH`. Search for "Additional ARCH settings" in the top-level Makefile to see cases where it doesn't.

`KERNELVERSION` is a version string. I've never seen anything depend on its exact value, but you can set it to the output of `make kernelversion` to be safe.

So, to run Kconfiglib on e.g. `ARCH=x86` without the Makefile targets, you can do this:

    $ ARCH=x86 SRCARCH=x86 KERNELVERSION=`make kernelversion` python
    >> import kconfiglib
    >> c = kconfiglib.Config() # defaults to loading "Kconfig"

That should match what you get with `scriptconfig` for any kernel version I've seen.

As for the thing you're trying to do, the approach I would use would be to iterate over the symbols that can be changed (`is_modifiable()`), changing them in strategic ways, and seeing if that alters the visibility of the "target" symbol. That way you could probably work out some kind of minimal set.

Note that this might get tricky in some cases since a symbol might depend on `A || B` or `!A` for example. If the only operator was `&&`, it would be easier to define what it means for one symbol to "require" another.

I'm currently working on a non-backwards-compatible 2.0 version of Kconfiglib by the way, with a much cleaned-up API ("less is more"). That one will also expose all the expressions in a clean way. It's safe to peek at them in the current version too if needed though, even though they're "internal".

Cheers,
Ulf

**Comment by ulfalizer** [comment]
For non-tricky cases (hopefully most of them), I think it would work to first keep setting symbols that can be modified until the target symbol becomes visible, and then unsetting symbols while it doesn't affect the visibility of the target. The symbols that remain after the second pass are the required ones.
