### ISSUE TITLE
kconfig validation

### ISSUE THREAD

**Issue by webknjaz** [ulfalizer/Kconfiglib#37]
Hello,

Is it possible to use this project for the purpose of validation of option dependencies in linux kernel config? if yes, could you please point to some specific doc/code where I could start. TIA.

**Comment by ulfalizer** [comment]
Hello,

If you want to check that each value set in a `defconfig` file matches the final value the symbol gets, then you could do the following, adapted from [merge_config.py](https://github.com/ulfalizer/Kconfiglib/blob/master/examples/merge_config.py):

```python
...
kconf.load_config(config_file_to_check)

# Print warnings for symbols whose actual value doesn't match the assigned
# value
for sym in kconf.defined_syms:
    # Was the symbol assigned to?
    if sym.user_value is not None:
        # Tristate values are represented as 0, 1, 2. Having them as
        # "n", "m", "y" is more convenient here, so convert.
        if sym.type in (BOOL, TRISTATE):
            user_value = TRI_TO_STR[sym.user_value]
        else:
            user_value = sym.user_value

        if user_value != sym.str_value:
            print('warning: {} was assigned the value "{}" but got the '
                  'value "{}" -- check dependencies'
                  .format(sym.name, user_value, sym.str_value))
```

This works fine for `defconfig` files, because you always expect the final value to match the assigned value in those (look up `make savedefconfig`). It might get a bit more iffy for old "full" `.config` files.

If you want to do a batch job over multiple `defconfig` files in the kernel, take a look at how the  [test_defconfig()](https://github.com/ulfalizer/Kconfiglib/blob/master/testsuite.py#L1984) test is implemented in the test suite. The [list_undefined.py](https://github.com/zephyrproject-rtos/Kconfiglib/blob/master/examples/list_undefined.py) script might give you some ideas too.

**Comment by webknjaz** [comment]
Thanks for the pointers :) I'll try

**Comment by ulfalizer** [comment]
Closing for now. Open another issue (or reopen this one, if that's possible) if you have other questions.
