### ISSUE TITLE
Unexpected behaviour when loading fragments

### ISSUE THREAD

**Issue by SebastianBoe** [ulfalizer/Kconfiglib#43]
Hi,

pretty sure this is a bug, but it is not easy to be certain with Kconfig ;)

Lowering a value in a fragment doesn't seem to work.

Steps to reproduce:

```
cd Kconfiglib/examples
git remote add sebo_remote https://github.com/SebastianBoe/Kconfiglib
git fetch --all
git checkout 34327f56891e2a6583df6d03144042084fca07a8
python merge_config.py Kconfig merged conf1 && cat merged 
```

Actual output:

```
sebo@mach:~/repos/kconfiglib_zephyr/examples$ python merge_config.py Kconfig merged conf1 && cat merged 
conf1:2: warning: BAR (defined at Kconfig:9) set more than once. Old value: "y", new value: "n".
warning: BAR (defined at Kconfig:9) was assigned the value "n" but got the value "y" -- check dependencies
# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)
# CONFIG_FOO is not set
CONFIG_BAR=y

```

Expected output:

```
sebo@mach:~/repos/kconfiglib_zephyr/examples$ python merge_config.py Kconfig merged conf1 && cat merged 
conf1:2: warning: BAR (defined at Kconfig:9) set more than once. Old value: "y", new value: "n".
# Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib)
CONFIG_FOO=y
# CONFIG_BAR is not set

```

Interestingly, removing CONFIG_BAR=y will give the expected behaviour, which leads me to believe one can not lower config values in fragments, which is unexpected as the warning states it is getting the new value.

PS: https://github.com/SebastianBoe/Kconfiglib/commit/34327f56891e2a6583df6d03144042084fca07a8

**Comment by ulfalizer** [comment]
This is due to some special behavior for choices. It will work as expected for non-choice symbols.

Setting a choice symbol to `y` also sets `Choice.user_selection` to that symbol. Setting it to `n` later doesn't change `Choice.user_selection`. Setting some other symbol in the choice to `y` would update the user selection though.

The only way to get rid of the user selection is to call `Choice.unset_value()`. The choice then reverts back to the default selection.

This behavior makes `.config` loading "just work" for choices. It is pretty unintuitive for the case above though. I guess you could unset `Choice.user_selection` if the `Choice.user_selection` symbol is set to `n`, which might make the above example more intuitive. I'm not sure it's worthwhile though. It's a bit weird to have setting a user value unset a different user value too.

Note that "no user value" and "user value n" are different btw.

**Comment by ulfalizer** [comment]
The C implementation works the same way btw, and has the same behavior there. It turns out that it's handiest to remember the choice selection separately.

Imagine if someone calls `set_value("y")` on a bunch of symbols in the same choice for example. In that case, what you probably want is to have the last symbol set to `y` be the user selection. At the same time, you don't want to have to update the user values of all the other choice symbols, as it gets messy in practice. It's also nice to have `Symbol.user_value` always reflect the assigned value.

There's a bunch of trickiness related to choices that isn't obvious until you try to implement them. Kconfiglib 1 handled them in a messier way, so I know the pain.

**Comment by ulfalizer** [comment]
Is this inspired by some real-world example btw?

**Comment by SebastianBoe** [comment]
"Is this inspired by some real-world example btw?"

Yes, turning off bluetooth log's in a bluetooth example.

e.g. 

CONFIG_BT_DEBUG_LOG=n

in mesh.

**Comment by ulfalizer** [comment]
@SebastianBoe 
Looking at `subsys/bluetooth/common/Kconfig`, the right way to override it might be to do `CONFIG_BT_DEBUG_NONE=y`. That will automatically unset `CONFIG_BT_DEBUG_LOG` in the final configuration as well, as `bool` choices have the constraint that only a single symbol can be `y`.

**Comment by ulfalizer** [comment]
Closing for now.
