### ISSUE TITLE
Print unmet dependency

### ISSUE THREAD

**Issue by oyvindronningstad** [ulfalizer/Kconfiglib#86]
When printing

    warning: MY_CONFIG (defined at ...) was assigned the value 'y' but got the value 'n'.

can we also print which dependency was not met? Sometimes it's non-trivial to figure out manually, especially if cmake fails so there's no `menuconfig` to run.

(Tell me if this issue should be opened in Zephyr instead)

**Comment by ulfalizer** [comment]
It gets tricky in the general case, because dependencies can get really complex, e.g.

```
depends on (FOO || BAR > 3) && (BAZ != "string" || QAZ = HMM)
```

Maybe it would be possible to split the expression into its top-level && components and print any n-valued ones as is though, so that it'd report that e.g. `(FOO || BAR >3)` isn't satisfied. Most cases would be simpler than that too.

That warning is implemented by `scripts/kconfig/kconfig.py` in Zephyr, so could open an issue there.

**Comment by oyvindronningstad** [comment]
Even just printing such a compound dependency would be helpful IMO.

Can this be fixed in Zephyr without changes in kconfiglib? If so I'll close this and open there.

**Comment by ulfalizer** [comment]
Yup, it's all implemented in `scripts/kconfig/kconfig.py`.
